### ISSUE TITLE
instructions on website to run docker don't work with last version

### ISSUE THREAD

**Issue by jeromecc** [neo4j/docker-neo4j#152] opened 2018-10-03 21:06 UTC
Hello!
Instructions are here: https://neo4j.com/developer/docker/

docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    neo4j:3.0

This works well.

But:
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    neo4j
Doesn't. This is pulling the latest version which is 3.4.7 at time of writing.

The instructions in the README.md file works well:
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j:3.0

Someone should update the website.

Thank you for the amazing work!

Cheers,

jérôme

**Comment by jennyowen** [comment] 2019-01-18 10:53
Thanks for reporting this.
It looks as though the logging may have changed in 3.1. If I don't specify subfolders it works as expected:
```
docker run 
--publish=7474:7474 --publish=7687:7687 
--volume=$HOME/neo4j:/data 
--volume=$HOME/neo4j:/logs 
neo4j
```
I can update the README here, it looks like our docs also have the broken code in. 
/cc @davidoliverSP2

**Comment by jennyowen** [comment] 2019-01-23 14:49
On further inspection, I think the documentation is actually correct.
This looks to be caused by file permissions on the non-containerised mount point for the `/logs`. Mounting `/data` seems to work file. 
The `docker-entrypoint.sh` is setting file ownership to `neo4j:neo4j` on `/data` but it misses out doing that for `/logs`.

**Comment by jennyowen** [comment] 2019-01-31 14:20
Fixed with https://github.com/neo4j/docker-neo4j/pull/161
This will be in all future Neo4j  docker releases, so from these versions and onwards:
- 3.5.3
- 3.4.13
- 3.3.10

This isn't a guarantee that we'll make those specific releases. More that if we release those versions, you'll be able to mount the `logs` directory in the same way as our documentation.

**Closed by jennyowen** 2019-01-31 14:20 UTC
Labels: bug
