### ISSUE TITLE
Documentation on how to use 2.3.3 Ha cluster in AWS ECS?

### ISSUE THREAD

**Issue by ashramsey** [neo4j/docker-neo4j#43] opened 2016-06-24 08:38 UTC
Trying to set up 1 docker container per ec2 instance, rather than 3 containers on 1 instance (as described https://neo4j.com/developer/docker-23/#).

Having trouble getting the containers to talk to each other when they arent in the same instance.

Has any one had any success with this using aws ecs clusters, services and taskDefinitions?

Thanks

**Comment by ashramsey** [comment] 2016-06-28 06:28
I think I've managed to narrow the issue I'm having. I have set up 3 containers each on their own ec2 instance. Each ec2 host instance has a given ip-address 10.1.1.25, 10.1.1.26, 10.1.2.27. Each container has a hostname set core1, core2, core3, mapped respectively to these host ip-addresses. And each container has these set in their /etc/hosts file so they know how to find these hostnames.

```
10.1.1.25 core1
10.1.1.26 core2
10.1.2.27 core3
```

In turn, for each container, I've set `NEO4J_HA_ADDRESS` as the respective hostname, and `NEO4J_INITIAL_HOSTS` as `core1:5001,core2:5001,core3:5001` 

So I expect any cluster node to be able to resolve the other nodes by port-mapping the host to the container as can be seen in the `docker ps` command, 

```
ubuntu@ip-10-1-2-27:~$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                                                                                      NAMES
3ac5f3ab8cc1        neo4j:2.3.3-enterprise           "/var/lib/neo4j/conf/"   17 hours ago        Up 17 hours         0.0.0.0:1337->1337/tcp, 0.0.0.0:5001->5001/tcp, 0.0.0.0:6001->6001/tcp, 0.0.0.0:7473-7474->7473-7474/tcp   ecs-Neo4j-HA-core3TaskDefinition-50JQ588IPY19-1-core3-94f896f4ebb1fde59201
162c9cd3ad74        amazon/amazon-ecs-agent:latest   "/agent"                 22 hours ago        Up 22 hours         127.0.0.1:51678->51678/tcp
```


So, in the data/graph.db/messages.log for eg core3, reports:

```
ClusterState: joining-[configurationRequest]->joining from:cluster://10.1.1.26:5001 conversation-id:2/13# payload:ConfigurationRequestState{joiningId=2, joiningUri=cluster://172.17.0.3:5001}
```

I'm thinking the issue might be the joiningUri. The endpoint is set as the container ip address despite setting the `NEO4J_HA_ADDRESS` as the hostname `core3`. As such, the endpoint is not reslved and the connection times out.

```
2016-06-27 08:27:57.967+0000 DEBUG [o.n.c.p.c.ClusterState$3] [AsyncLog @ 2016-06-27 08:27:57.967+0000]  ClusterState: joining-[joiningTimeout]->discovery conversation-id:3/13# payload:cluster://10.1.1.25:5001
2016-06-27 08:27:57.967+0000 DEBUG [o.n.c.p.h.HeartbeatState$1] [AsyncLog @ 2016-06-27 08:27:57.967+0000]  HeartbeatState: start-[reset_send_heartbeat]->start conversation-id:3/13#
2016-06-27 08:27:57.970+0000 DEBUG [o.n.c.p.c.ClusterState$2] [AsyncLog @ 2016-06-27 08:27:57.970+0000]  ClusterState: discovery-[configurationRequest]->discovery from:cluster://172.17.0.3:5001 conversation-id:3/13# payload:ConfigurationRequestState{joiningId=3, joiningUri=cluster://172.17.0.3:5001}
2016-06-27 08:27:57.972+0000 INFO  [o.n.c.p.c.ClusterState] [AsyncLog @ 2016-06-27 08:27:57.971+0000]  Joining cluster neo4j.ha
2016-06-27 08:27:57.972+0000 INFO  [o.n.c.p.c.ClusterState] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  3 joining:Name:neo4j.ha Nodes:{1=cluster://172.17.0.3:5001} Roles:{coordinator=1}, last delivered:2
2016-06-27 08:27:57.972+0000 DEBUG [o.n.c.p.c.ClusterState] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  Setup join timeout for 3/13#
2016-06-27 08:27:57.972+0000 DEBUG [o.n.c.p.c.ClusterState$2] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  ClusterState: discovery-[configurationResponse]->joining from:cluster://10.1.1.25:5001 conversation-id:3/13# payload:ConfigurationResponseState{nodes={1=cluster://172.17.0.3:5001}, latestReceivedInstanceId=2, roles={coordinator=1}, clusterName='neo4j.ha'}
2016-06-27 08:27:57.973+0000 DEBUG [o.n.c.p.h.HeartbeatState$1] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  HeartbeatState: start-[reset_send_heartbeat]->start conversation-id:3/13# payload:1
2016-06-27 08:27:57.973+0000 DEBUG [o.n.c.p.a.m.AtomicBroadcastState$2] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  AtomicBroadcastState: joining-[join]->joining conversation-id:3/13#
2016-06-27 08:27:57.973+0000 DEBUG [o.n.c.p.a.m.LearnerState$2] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  LearnerState: learner-[join]->learner conversation-id:3/13#
2016-06-27 08:27:57.974+0000 DEBUG [o.n.c.p.a.m.AcceptorState$2] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  AcceptorState: acceptor-[join]->acceptor conversation-id:3/13#
2016-06-27 08:27:57.974+0000 DEBUG [o.n.c.p.h.HeartbeatState$1] [AsyncLog @ 2016-06-27 08:27:57.972+0000]  HeartbeatState: start-[i_am_alive]->start from:cluster://10.1.1.25:5001 conversation-id:3/13# payload:i_am_alive[1]
2016-06-27 08:27:57.974+0000 DEBUG [o.n.c.p.a.m.ProposerState$1] [AsyncLog @ 2016-06-27 08:27:57.973+0000]  ProposerState: start-[propose]->start from:cluster://172.17.0.3:5001 conversation-id:3/13# payload:Change cluster config, join:3
2016-06-27 08:28:17.463+0000 DEBUG [o.n.c.p.c.ClusterState$3] [AsyncLog @ 2016-06-27 08:28:17.463+0000]  ClusterState: joining-[configurationRequest]->joining from:cluster://10.1.1.26:5001 conversation-id:2/13# payload:ConfigurationRequestState{joiningId=2, joiningUri=cluster://172.17.0.3:5001}
2016-06-27 08:28:27.969+0000 INFO  [o.n.c.p.c.ClusterState] [AsyncLog @ 2016-06-27 08:28:27.968+0000]  Join timeout for 3/13#
```


So I'm wondering if this might be a bug? Should the `joiningUri=cluster://172.17.0.3:5001` actually contain the hostname `joiningUri=cluster://core3:5001`?

The problem with the ip address `172.17.0.3` is that it is the same one used for each container, so I cant easily resolve this.

Any direction would be much appreciated.

Thanks

**Comment by benbc** [comment] 2016-06-30 07:31
@spacecowboy I think you're the current expert in this area. Are we resolving the HA address to an IP before publishing it to the rest of the cluster?

**Comment by spacecowboy** [comment] 2016-06-30 08:23
We are indeed resolving into IP-addresses in HA, but that is probably not the problem.

@ashramsey Is it possible for you to try 2.3.4 or 2.3.5? (just creating a test cluster with no production data is fine) I am wondering if https://github.com/neo4j/neo4j/pull/6562 might not be included in that version (despite what the changelog says).

**Comment by spacecowboy** [comment] 2016-06-30 08:31
Hmm, running an actual check, that PR is included in 2.3.3 so 2.3.4 should not make any difference in regards to that.

Might be the case that the joiningUri is wrongly constructed

**Comment by ashramsey** [comment] 2016-06-30 08:43
Hi, I'm a bit out of my depth here, so forgive me if Im stating the obvious, but if it helps...

I think it has something to do with the neo4j process using the local interface ip-address. The link:

http://neo4j.com/docs/2.3.3/ha-setup-tutorial.html#_ha_server

says it binds to the hosts network-interface. In the case of a dockerised neo4j process, this would be docker0 interface by default, and not the underlying ec2 instance's network interface. hence the 172.17.0.3:5001 and not 10.1.0.0/16 cidr.

From what aws support says, there is no option for --net=host or eta to support it. So I ditched ecs and have used the docker run command, as in your docs. And have managed to get a cluster running on 2.3.3 on 3 separate ec2 instances.



I'm happy to go down this path than trying to force aws ecs, so feel free to close if you want.

**Comment by spacecowboy** [comment] 2016-06-30 10:33
If that works for you, great!

But binding to the container's network interface it the correct, and _only_, thing it can do. The problem is what is advertised to the rest of the cluster, which you demonstrated was the wrong ip. Specifying the IP manually _should_ correct the issue.

**Comment by benbc** [comment] 2016-08-24 05:48
@spacecowboy Do we need to do anything here?

**Comment by spacecowboy** [comment] 2016-09-12 08:04
@benbc I don't believe so

**Closed** 2016-09-12 08:21 UTC
