### ISSUE TITLE
uid and gid change

### ISSUE THREAD

**Issue by johanlundberg** [neo4j/docker-neo4j#266] opened 2020-07-17 12:25 UTC
When changing to explicit uid and gid as in https://github.com/neo4j/docker-neo4j/commit/b65ad72670af729d2cf267e5891faf2c790de2e9#diff-1a242d50ea39764c397415128f5c75b2 please make sure to chown already created files that need to be readable and writable in the entrypoint script.

The fix for my issue was simple to do (chown my existing database files to 7474:7474) but it took a while to figure out what had changed.

**Comment by jennyowen** [comment] 2020-07-17 13:56
How did you reproduce this?
There is already code in the entrypoint which will `chown` the various folders that require write access.

I tried reproducing this locally by doing:
```
mkdir {data,logs,plugins,certificates,conf,import,metrics}

docker run -it --rm \
--publish=7474:7474 --publish=7687:7687 \
--volume=$PWD/data:/data \
--volume=$PWD/logs:/logs \
--volume=$PWD/plugins:/plugins \
--volume=$PWD/certificates:/certificates \
--volume=$PWD/conf:/conf \
--volume=$PWD/import:/import \
--volume=$PWD/metrics:/metrics \
-e NEO4J_AUTH=none \
neo4j:4.0.0
```
and `stat $PWD/data` folder showed uid 101, which is expected. Then I started a newer image:
```
docker run -it --rm \
--publish=7474:7474 --publish=7687:7687 \
--volume=$PWD/data:/data \
--volume=$PWD/logs:/logs \
--volume=$PWD/plugins:/plugins \
--volume=$PWD/certificates:/certificates \
--volume=$PWD/conf:/conf \
--volume=$PWD/import:/import \
--volume=$PWD/metrics:/metrics \
-e NEO4J_AUTH=none \
neo4j:4.1.1
```
and was able to start neo4j and read from the database. Doing `stat data` afterwards showed the folder was owned by uid/gid 7474.
Maybe you are mounting things differently, or maybe you're upgrading from a different version?

**Comment by johanlundberg** [comment] 2020-07-20 08:35
I am using a datavolume for /data, this is what it looks like when I try the above with my setup. This time I notice that the exception actually tells me about the problem arising from file permission trouble. I don't know if I didn't see that the first time or if it is new :)

In this setup I have only ran versions 4.0.X and 4.1.X.

```
$ docker run -it --rm --publish=7474:7474 --publish=7687:7687 --volume=testneo4jdata:/data \ 
  --env NEO4J_AUTH=neo4j/docker --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \ 
  neo4j:4.0.0-enterprise
Unable to find image 'neo4j:4.0.0-enterprise' locally
4.0.0-enterprise: Pulling from library/neo4j
8559a31e96f4: Already exists 
65306eca6b8e: Already exists 
ddbf88050b6e: Already exists 
f8fd11959573: Already exists 
0f32bbd840f9: Pull complete 
3a5f32cbdf79: Pull complete 
fc6b5f2b3c5a: Pull complete 
3f74f74017e1: Pull complete 
Digest: sha256:fd894d4c6cb5adcdfb4d2894e0eff136763138ae0da4c4be28c434b88677b332
Status: Downloaded newer image for neo4j:4.0.0-enterprise
Changed password for user 'neo4j'.
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-07-20 08:16:58.072+0000 INFO  ======== Neo4j 4.0.0 ========
2020-07-20 08:16:58.080+0000 INFO  Starting...
2020-07-20 08:17:03.095+0000 INFO  Sending metrics to CSV file at /var/lib/neo4j/metrics
2020-07-20 08:17:03.125+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-07-20 08:17:03.125+0000 INFO  Started.
2020-07-20 08:17:03.385+0000 INFO  Server thread metrics have been registered successfully
2020-07-20 08:17:04.441+0000 INFO  Remote interface available at http://0.0.0.0:7474/
^C2020-07-20 08:18:43.898+0000 INFO  Neo4j Server shutdown initiated by request
2020-07-20 08:18:43.920+0000 INFO  Stopping...
2020-07-20 08:18:49.176+0000 INFO  Stopped.
$ docker run -it --rm --publish=7474:7474 --publish=7687:7687 --volume=testneo4jdata:/data \
  --env NEO4J_AUTH=neo4j/docker --env NEO4J_ACCEPT_LICENSE_AGREEMENT=yes \
  neo4j:4.1-enterprise
Warning: Folder mounted to "/data/dbms" is not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-07-20 08:18:57.209+0000 INFO  Starting...
2020-07-20 08:19:00.066+0000 INFO  ======== Neo4j 4.1.1 ========
2020-07-20 08:19:05.281+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at com.neo4j.server.enterprise.EnterpriseManagementServiceFactory.createManagementService(EnterpriseManagementServiceFactory.java:38)
	at com.neo4j.server.enterprise.EnterpriseBootstrapper.createNeo(EnterpriseBootstrapper.java:20)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at com.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:25)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.LockerLifecycleAdapter@5965be2d' was successfully initialized, but failed to start. Please see the attached cause exception "/data/databases/store_lock".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)	
	... 6 more
Caused by: org.neo4j.kernel.internal.locker.FileLockException: Unable to obtain lock on file: /data/databases/store_lock: Owner of the lock file '101' and user running this process 'neo4j' differs, which means this could be a file permission problem. Ensure that the lock file has the same owner, or at least has write access for the user running the Neo4j process trying to lock it. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.Locker.storeLockException(Locker.java:176)
	at org.neo4j.kernel.internal.locker.Locker.unableToObtainLockException(Locker.java:169)
	at org.neo4j.kernel.internal.locker.Locker.checkLock(Locker.java:108)
	at org.neo4j.kernel.internal.locker.GlobalFileLocker.checkLock(GlobalFileLocker.java:58)
	at org.neo4j.kernel.internal.locker.GlobalLocker.checkLock(GlobalLocker.java:28)
	at org.neo4j.kernel.internal.locker.LockerLifecycleAdapter.start(LockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	... 8 more
Caused by: java.nio.file.AccessDeniedException: /data/databases/store_lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:71)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.write(DefaultFileSystemAbstraction.java:102)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.write(DefaultFileSystemAbstraction.java:53)
	at org.neo4j.kernel.internal.locker.Locker.checkLock(Locker.java:90)
	... 12 more
2020-07-20 08:19:05.281+0000 INFO  Neo4j Server shutdown initiated by request
```
File permissions after first 4.0,
```
$ docker volume inspect testneo4jdata
[
    {
        "CreatedAt": "2020-07-20T10:16:55+02:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/testneo4jdata/_data",
        "Name": "testneo4jdata",
        "Options": {},
        "Scope": "local"
    }
]
# cd /var/lib/docker/volumes/testneo4jdata/_data
# ls -la
total 20
drwxrwxrwx 5 systemd-network systemd-journal 4096 jul 20 10:16 .
drwxr-xr-x 3 root            root            4096 jul 20 10:09 ..
drwxrwxrwx 4 systemd-network systemd-journal 4096 jul 20 10:17 databases
drwxr-xr-x 2 systemd-network systemd-journal 4096 jul 20 10:16 dbms
drwxrwxrwx 4 systemd-network systemd-journal 4096 jul 20 10:17 transactions
# stat .
  File: .
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d	Inode: 52297730    Links: 5
Access: (0777/drwxrwxrwx)  Uid: (  101/systemd-network)   Gid: (  101/systemd-journal)
Access: 2020-07-20 10:18:16.007537170 +0200
Modify: 2020-07-20 10:16:55.983594405 +0200
Change: 2020-07-20 10:16:55.983594405 +0200
 Birth: -
```
After second run, 4.1.1:
```
# stat .
  File: .
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: fd01h/64769d	Inode: 52297730    Links: 5
Access: (0777/drwxrwxrwx)  Uid: (  101/systemd-network)   Gid: (  101/systemd-journal)
Access: 2020-07-20 10:18:16.007537170 +0200
Modify: 2020-07-20 10:16:55.983594405 +0200
Change: 2020-07-20 10:16:55.983594405 +0200
 Birth: -
```

**Comment by jennyowen** [comment] 2020-07-22 13:01
Thanks for the reproduction code, you're right, I've been able to verify the bug myself. 
I'm not sure why named volumes and file mounts seem to behave differently or respond differently when we check ownership. I'll have to investigate.

**Comment by jennyowen** [comment] 2020-07-30 11:10
I investigated this, and it looks as though, with named volumes, `/data` and `/logs` are by default give `777` (full rwx access to everybody) file permissions as specified in the Dockerfile. For file system mounting, the folders have permissions `755`.

In the entrypoint, we check the *folder* permissions to see if the folder is writable and perform a `chown` if it's not. 
The *files* in `/data` and `/logs` are created and owned by the `neo4j` user inside the container. When the `uid` of `neo4j` changed, the new `neo4j` user could no longer write to those files.
With file system mounting, the uid change made the folder unwritable, so it prompted a `chown` and so it works. With named volume mounting, folder permissions stay as `777` and the folder stays writable and did not prompt a chown. The database *files* stayed unwritable, and so neo4j failed. 

I've created pull request #270 to add a permissions check on the files and chown if there are any unwritable files. I also improved unit testing around this use case, and around upgrading in general.

**Comment by jennyowen** [comment] 2020-07-30 13:51
OK the fix is now merged. It should be included from Neo4j 4.0.8 and 4.1.2 onwards.

**Closed by jennyowen** 2020-07-30 13:51 UTC

**Comment by masuar** [comment] 2020-08-27 09:31
Hi, I am not familiar with your pace of releasing to Docker Hub. When it is supposed this fix will be there?

**Comment by jennyowen** [comment] 2020-08-27 10:07
@masuar we release to docker hub whenever there's a new Neo4j release. For major/minor releases that's twice a year, but for patch releases we release whenever an enterprise customer wants a fix OR if we feel it's been too long without a patch update. That generally means we have at least one patch every 3 or 4 weeks, but there's a bit of variation. Neo4j 4.0.8 is actually being prepared for release right now.

I don't tend to go back and edit already released images unless the bug is quite bad.

**That being said**, this particular bug actually ended up breaking some training material, so I had to go and retroactively apply this fix to 4.0.7 and 4.1.1. 
If you're interested, the source code for the images on Dockerhub is pulled from here:
https://github.com/neo4j/docker-neo4j-publish

**Comment by masuar** [comment] 2020-08-27 10:22
Thank you for your prompt reply! that means that the fix is already included in 4.1.1, right? 

We are spinning "latest", and we are seeing some very similar behaviour to the one described in this issue. But if the fix is already applies, it might be something else then.

**Comment by jennyowen** [comment] 2020-08-27 10:58
> that means that the fix is already included in 4.1.1, right?

correct!

Permissions errors are quite common with our image because we use a user that only exists in the container. What is the docker command you're running that gets the error and what is the error?

**Comment by masuar** [comment] 2020-08-27 11:56
We use Docker Swarm. DockerCompose file is defining 3 volumes (import, plugins, and data) and exposing the usual ports. We tried without changing the user, and with a "real" user. We also tried chmodding to 755 and 777 all folders and files. Same result in both cases:

Directories in use:
home: /var/lib/neo4j
config: /var/lib/neo4j/conf
logs: /logs
plugins: /var/lib/neo4j/plugins
import: /var/lib/neo4j/import
data: /var/lib/neo4j/data/
certificates: /var/lib/neo4j/certificates
run: /var/lib/neo4j/run
Starting Neo4j.
APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix.
2020-08-24 08:00:08.704+0000 INFO Starting...
2020-08-24 08:00:14.040+0000 INFO ======== Neo4j 4.1.1 ========
020-08-24 08:00:26.245+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address. Error starting Neo4j database server at /data/databases
java.lang.RuntimeException: Error starting Neo4j database server at /data/databases
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:198)
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.LockerLifecycleAdapter@3eb91815' was successfully initialized, but failed to start. Please see the attached cause exception "No locks available".
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:463)
at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
... 5 more
Caused by: org.neo4j.kernel.internal.locker.FileLockException: Unable to obtain lock on file: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
at org.neo4j.kernel.internal.locker.Locker.storeLockException(Locker.java:176)
at org.neo4j.kernel.internal.locker.Locker.unableToObtainLockException(Locker.java:169)
at org.neo4j.kernel.internal.locker.Locker.checkLock(Locker.java:108)
at org.neo4j.kernel.internal.locker.GlobalFileLocker.checkLock(GlobalFileLocker.java:58)
at org.neo4j.kernel.internal.locker.GlobalLocker.checkLock(GlobalLocker.java:28)
at org.neo4j.kernel.internal.locker.LockerLifecycleAdapter.start(LockerLifecycleAdapter.java:36)
at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
... 7 more
Caused by: java.io.IOException: No locks available
at java.base/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
at java.base/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1161)
at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
at org.neo4j.io.fs.StoreFileChannel.tryLock(StoreFileChannel.java:299)
at org.neo4j.kernel.internal.locker.Locker.checkLock(Locker.java:92)
... 11 more
2020-08-24 08:00:26.246+0000 INFO Neo4j Server shutdown initiated by request

**Comment by jennyowen** [comment] 2020-08-27 13:15
@masuar that could be a regular store lock error instead of something to do with permissions. 
Possibly also a neo4j container wasn't able to close down cleanly at some point and didn't delete its lock?

 Make sure there are no running neo4j containers and delete the store lock file and try again. 

If it still fails, could you create a new issue and include reproduction code?
