### ISSUE TITLE
Upgrading from 3.5.5 to 3.5.6 with Docker Image fails with permission denied

### ISSUE THREAD

**Issue by Stubatiger** [neo4j/docker-neo4j#207] opened 2019-11-12 09:33 UTC
If i try to upgrade neo4j in my dockerfile from 3.5.5 to 3.5.6, i can not start the container again because it fails with the message:

> /var/lib/neo4j/bin/neo4j: line 259: /var/lib/neo4j/conf/neo4j.conf: Permission denied

**Neo4j Version:** 3.5.6 
**Operating System:** Ubuntu 16.04.6
**API:** Docker (Docker version 19.03.4, build 9013bf583a)

### Steps to reproduce
1. Pull the image: `docker pull neo4j:3.5.6`
2. Start it: `docker run -it neo4j:3.5.6`

### Expected behavior
Neo4j container should start up

### Actual behavior
Neo4j container fails with permission error

Terminal-Log:

> $ docker pull neo4j:3.5.6
> 3.5.6: Pulling from library/neo4j
> Digest: sha256:a7589a48db5d8846dd8db68dc52eb20fa1a29fa74b2bc16035789f10101f9035
> Status: Image is up to date for neo4j:3.5.6
> docker.io/library/neo4j:3.5.6
> $ docker run -it neo4j:3.5.6
> /var/lib/neo4j/bin/neo4j: line 255: /var/lib/neo4j/conf/neo4j.conf: Permission denied

**Comment by jennyowen** [comment] 2019-11-18 08:47
@Stubatiger for 3.5.6 we made some significant changes to how the Neo4j docker image handles file permissions in mounted volumes since we were getting a LOT of users with issues about it. See:
https://github.com/neo4j/docker-neo4j/issues/131#issuecomment-489612338

Following your reproduction steps -running `neo4j:3.5.6` without mounting anything- works for me so I can't reproduce your issue. Are you sure you're not mounting any folders? You mentioned that you have a Dockerfile which I guess uses `neo4j:3.5.6` as the base image?

**Comment by mirceaalexruse** [comment] 2019-11-25 13:13
In my case, the issue got solved by specifying the UUID **and** GUID in my compose file (as per comment #131 ).  I am using root in my exampe, but it works for any uuid/guid, as long as they are **both** specified...
My setup is a bit unorthodox: I am mounting a volume, then I use env vars to set up which directories my containers should write to. I am forced to do this in my usecase

Here's a sample:
    image: neo4j
    container_name: <somename>
    restart: unless-stopped
    **user: "0:0"**
    environment:
      NEO4J_dbms_directories_data: /unprocessed/data
      NEO4J_dbms_directories_import: /unprocessed/import
      NEO4J_dbms_directories_plugins: /unprocessed/plugins
      NEO4J_dbms_directories_logs: /unprocessed/logs
      NEO4J_dbms_directories_metrics: /unprocessed/metrics

    volumes:
      - Unprocessed:/unprocessed

_Unrelated:_
When deploying the stack, two extra volumes are created: one for data and one for logs. However, they are only used when bringing the container up (which is specified in the Dockerfile). 

/testdata# ls
databases  dbms
/testdata# ls */*
dbms/auth.ini


as opposed to the actual volume:
/Unprocessed/data/databases # ls
graph.db    store_lock

**Comment by jennyowen** [comment] 2019-12-03 08:38
I'm going to close this issue because there was a much older issue that just got moved over from the neo4j/neo4j repository #212 which I believe is the same as this one.
Here's the explanation as to why it's happening https://github.com/neo4j/docker-neo4j/issues/212#issuecomment-560437102
Basically we check the `neo4j` user is in the owning group, but don't check that the folders allow group write.

**Closed by jennyowen** 2019-12-03 08:38 UTC
Labels: need more info
